name: 3dpipe
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.8         # match your GPU & CUDA
  - pip:
    - torch
    - torchvision
    - pytorch-lightning
    - exifread
    - opencv-python
    - pillow
    - hydra-core
    - dvc
    - wandb
    - rembg
    - segmentation-models-pytorch
